export class Article {
  constructor(
    public id: any = '',
    public title: string = '',
    public title_en_gb: string = '',
    public title_fr_fr: string = '',
    public title_cn_cn: string = '',
    public price: any = '',
    public birth: any = '',
    public size: any = '',
    public theme: any = '',
    public material: any = '',
    public discount: any = '',
    public artist: any = '',
    public dynasty: any = '',
    public museum: any = '',
    public product: any = '',
    public form: any = '',
    public description_en_gb: string = '',
    public description_fr_fr: string = '',
    public description_cn_cn: string = '',
    public highlight: any = '0',
    //public sizes: any  = '',
    public file: string = '',
    public fileSource: any = '',
  ) {}
}